title:            ¬Ûπ»Ã«
description:      A jekyll theme.≤‚ ‘”√µƒ.
url:              mgtang.github.io # Site url.
signoff:          ¬Ûπ»Ã« # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://mgtang.github.io
    external:     true
  - name:         Email
    url:          mailto:#
    external:     true
  - name:         GitHub
    url:          http://github.com/mgtang
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
